// <auto-generated />
using System;
using Lecture_web;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lecture_web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Lecture_web.Models.BaiGiangModels", b =>
                {
                    b.Property<int>("IdBaiGiang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBaiGiang"));

                    b.Property<int>("IdTaiKhoan")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("TaiKhoanIdTaiKhoan")
                        .HasColumnType("int");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdBaiGiang");

                    b.HasIndex("TaiKhoanIdTaiKhoan");

                    b.ToTable("BaiGiang");
                });

            modelBuilder.Entity("Lecture_web.Models.BaiModels", b =>
                {
                    b.Property<int>("IdBai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBai"));

                    b.Property<int>("ChuongIdChuong")
                        .HasColumnType("int");

                    b.Property<int>("IdChuong")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDungText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TieuDeBai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdBai");

                    b.HasIndex("ChuongIdChuong");

                    b.ToTable("Bai");
                });

            modelBuilder.Entity("Lecture_web.Models.BinhLuanModels", b =>
                {
                    b.Property<int>("IdBinhLuan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBinhLuan"));

                    b.Property<int>("BaiIdBai")
                        .HasColumnType("int");

                    b.Property<int>("BinhLuanChaIdBinhLuan")
                        .HasColumnType("int");

                    b.Property<int>("IdBai")
                        .HasColumnType("int");

                    b.Property<int?>("IdBinhLuanCha")
                        .HasColumnType("int");

                    b.Property<int>("IdTaiKhoan")
                        .HasColumnType("int");

                    b.Property<int?>("IdThongBao")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TaiKhoanIdTaiKhoan")
                        .HasColumnType("int");

                    b.Property<int>("ThongBaoIdThongBao")
                        .HasColumnType("int");

                    b.HasKey("IdBinhLuan");

                    b.HasIndex("BaiIdBai");

                    b.HasIndex("BinhLuanChaIdBinhLuan");

                    b.HasIndex("TaiKhoanIdTaiKhoan");

                    b.HasIndex("ThongBaoIdThongBao");

                    b.ToTable("BinhLuan");
                });

            modelBuilder.Entity("Lecture_web.Models.BoMonModels", b =>
                {
                    b.Property<int>("IdBoMon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBoMon"));

                    b.Property<int>("IdKhoa")
                        .HasColumnType("int");

                    b.Property<int>("KhoaIdKhoa")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenBoMon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdBoMon");

                    b.HasIndex("KhoaIdKhoa");

                    b.ToTable("BoMon");
                });

            modelBuilder.Entity("Lecture_web.Models.ChuongModels", b =>
                {
                    b.Property<int>("IdChuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdChuong"));

                    b.Property<int>("BaiGiangIdBaiGiang")
                        .HasColumnType("int");

                    b.Property<int>("IdBaiGiang")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenChuong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdChuong");

                    b.HasIndex("BaiGiangIdBaiGiang");

                    b.ToTable("Chuong");
                });

            modelBuilder.Entity("Lecture_web.Models.HocPhanModels", b =>
                {
                    b.Property<int>("IdHocPhan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHocPhan"));

                    b.Property<int>("BoMonIdBoMon")
                        .HasColumnType("int");

                    b.Property<int>("IdBoMon")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenHocPhan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdHocPhan");

                    b.HasIndex("BoMonIdBoMon");

                    b.ToTable("HocPhan");
                });

            modelBuilder.Entity("Lecture_web.Models.KhoaModels", b =>
                {
                    b.Property<int>("IdKhoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdKhoa"));

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenKhoa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdKhoa");

                    b.ToTable("Khoa");
                });

            modelBuilder.Entity("Lecture_web.Models.LopHocPhanModels", b =>
                {
                    b.Property<int>("IdLopHocPhan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLopHocPhan"));

                    b.Property<string>("AnhDaiDien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BaiGiangIdBaiGiang")
                        .HasColumnType("int");

                    b.Property<int>("HocPhanIdHocPhan")
                        .HasColumnType("int");

                    b.Property<int?>("IdBaiGiang")
                        .HasColumnType("int");

                    b.Property<int>("IdHocPhan")
                        .HasColumnType("int");

                    b.Property<int>("IdTaiKhoan")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("TaiKhoanIdTaiKhoan")
                        .HasColumnType("int");

                    b.Property<string>("TenLop")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdLopHocPhan");

                    b.HasIndex("BaiGiangIdBaiGiang");

                    b.HasIndex("HocPhanIdHocPhan");

                    b.HasIndex("TaiKhoanIdTaiKhoan");

                    b.ToTable("LopHocPhan");
                });

            modelBuilder.Entity("Lecture_web.Models.LopHocPhan_SinhVienModels", b =>
                {
                    b.Property<int>("IdLopHocPhan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLopHocPhan"));

                    b.Property<int>("IdTaiKhoan")
                        .HasColumnType("int");

                    b.Property<int>("LopHocPhanIdLopHocPhan")
                        .HasColumnType("int");

                    b.Property<int>("TaiKhoanIdTaiKhoan")
                        .HasColumnType("int");

                    b.HasKey("IdLopHocPhan");

                    b.HasIndex("LopHocPhanIdLopHocPhan");

                    b.HasIndex("TaiKhoanIdTaiKhoan");

                    b.ToTable("LopHocPhan_SinhVien");
                });

            modelBuilder.Entity("Lecture_web.Models.OtpModels", b =>
                {
                    b.Property<int>("OtpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OtpId"));

                    b.Property<int>("IdTaiKhoan")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayHetHan")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("OtpCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TaiKhoanIdTaiKhoan")
                        .HasColumnType("int");

                    b.HasKey("OtpId");

                    b.HasIndex("TaiKhoanIdTaiKhoan");

                    b.ToTable("OTP");
                });

            modelBuilder.Entity("Lecture_web.Models.TaiKhoanModels", b =>
                {
                    b.Property<int>("IdTaiKhoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTaiKhoan"));

                    b.Property<string>("AnhDaiDien")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdTaiKhoan");

                    b.ToTable("TaiKhoan");
                });

            modelBuilder.Entity("Lecture_web.Models.ThongBaoModels", b =>
                {
                    b.Property<int>("IdThongBao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdThongBao"));

                    b.Property<int>("IdLopHocPhan")
                        .HasColumnType("int");

                    b.Property<int>("IdTaiKhoan")
                        .HasColumnType("int");

                    b.Property<int>("LopHocPhanIdLopHocPhan")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TaiKhoanIdTaiKhoan")
                        .HasColumnType("int");

                    b.HasKey("IdThongBao");

                    b.HasIndex("LopHocPhanIdLopHocPhan");

                    b.HasIndex("TaiKhoanIdTaiKhoan");

                    b.ToTable("ThongBao");
                });

            modelBuilder.Entity("Lecture_web.Models.BaiGiangModels", b =>
                {
                    b.HasOne("Lecture_web.Models.TaiKhoanModels", "TaiKhoan")
                        .WithMany("BaiGiangs")
                        .HasForeignKey("TaiKhoanIdTaiKhoan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("Lecture_web.Models.BaiModels", b =>
                {
                    b.HasOne("Lecture_web.Models.ChuongModels", "Chuong")
                        .WithMany("Bais")
                        .HasForeignKey("ChuongIdChuong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chuong");
                });

            modelBuilder.Entity("Lecture_web.Models.BinhLuanModels", b =>
                {
                    b.HasOne("Lecture_web.Models.BaiModels", "Bai")
                        .WithMany("BinhLuans")
                        .HasForeignKey("BaiIdBai")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lecture_web.Models.BinhLuanModels", "BinhLuanCha")
                        .WithMany("PhanHoi")
                        .HasForeignKey("BinhLuanChaIdBinhLuan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lecture_web.Models.TaiKhoanModels", "TaiKhoan")
                        .WithMany("BinhLuans")
                        .HasForeignKey("TaiKhoanIdTaiKhoan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lecture_web.Models.ThongBaoModels", "ThongBao")
                        .WithMany("BinhLuans")
                        .HasForeignKey("ThongBaoIdThongBao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bai");

                    b.Navigation("BinhLuanCha");

                    b.Navigation("TaiKhoan");

                    b.Navigation("ThongBao");
                });

            modelBuilder.Entity("Lecture_web.Models.BoMonModels", b =>
                {
                    b.HasOne("Lecture_web.Models.KhoaModels", "Khoa")
                        .WithMany("BoMons")
                        .HasForeignKey("KhoaIdKhoa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Khoa");
                });

            modelBuilder.Entity("Lecture_web.Models.ChuongModels", b =>
                {
                    b.HasOne("Lecture_web.Models.BaiGiangModels", "BaiGiang")
                        .WithMany("Chuongs")
                        .HasForeignKey("BaiGiangIdBaiGiang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaiGiang");
                });

            modelBuilder.Entity("Lecture_web.Models.HocPhanModels", b =>
                {
                    b.HasOne("Lecture_web.Models.BoMonModels", "BoMon")
                        .WithMany("HocPhans")
                        .HasForeignKey("BoMonIdBoMon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BoMon");
                });

            modelBuilder.Entity("Lecture_web.Models.LopHocPhanModels", b =>
                {
                    b.HasOne("Lecture_web.Models.BaiGiangModels", "BaiGiang")
                        .WithMany("LopHocPhans")
                        .HasForeignKey("BaiGiangIdBaiGiang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lecture_web.Models.HocPhanModels", "HocPhan")
                        .WithMany("LopHocPhans")
                        .HasForeignKey("HocPhanIdHocPhan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lecture_web.Models.TaiKhoanModels", "TaiKhoan")
                        .WithMany("LopHocPhans")
                        .HasForeignKey("TaiKhoanIdTaiKhoan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaiGiang");

                    b.Navigation("HocPhan");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("Lecture_web.Models.LopHocPhan_SinhVienModels", b =>
                {
                    b.HasOne("Lecture_web.Models.LopHocPhanModels", "LopHocPhan")
                        .WithMany("LopHocPhan_SinhViens")
                        .HasForeignKey("LopHocPhanIdLopHocPhan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lecture_web.Models.TaiKhoanModels", "TaiKhoan")
                        .WithMany("LopHocPhan_SinhViens")
                        .HasForeignKey("TaiKhoanIdTaiKhoan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LopHocPhan");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("Lecture_web.Models.OtpModels", b =>
                {
                    b.HasOne("Lecture_web.Models.TaiKhoanModels", "TaiKhoan")
                        .WithMany("OTPs")
                        .HasForeignKey("TaiKhoanIdTaiKhoan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("Lecture_web.Models.ThongBaoModels", b =>
                {
                    b.HasOne("Lecture_web.Models.LopHocPhanModels", "LopHocPhan")
                        .WithMany("ThongBaos")
                        .HasForeignKey("LopHocPhanIdLopHocPhan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lecture_web.Models.TaiKhoanModels", "TaiKhoan")
                        .WithMany("ThongBaos")
                        .HasForeignKey("TaiKhoanIdTaiKhoan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LopHocPhan");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("Lecture_web.Models.BaiGiangModels", b =>
                {
                    b.Navigation("Chuongs");

                    b.Navigation("LopHocPhans");
                });

            modelBuilder.Entity("Lecture_web.Models.BaiModels", b =>
                {
                    b.Navigation("BinhLuans");
                });

            modelBuilder.Entity("Lecture_web.Models.BinhLuanModels", b =>
                {
                    b.Navigation("PhanHoi");
                });

            modelBuilder.Entity("Lecture_web.Models.BoMonModels", b =>
                {
                    b.Navigation("HocPhans");
                });

            modelBuilder.Entity("Lecture_web.Models.ChuongModels", b =>
                {
                    b.Navigation("Bais");
                });

            modelBuilder.Entity("Lecture_web.Models.HocPhanModels", b =>
                {
                    b.Navigation("LopHocPhans");
                });

            modelBuilder.Entity("Lecture_web.Models.KhoaModels", b =>
                {
                    b.Navigation("BoMons");
                });

            modelBuilder.Entity("Lecture_web.Models.LopHocPhanModels", b =>
                {
                    b.Navigation("LopHocPhan_SinhViens");

                    b.Navigation("ThongBaos");
                });

            modelBuilder.Entity("Lecture_web.Models.TaiKhoanModels", b =>
                {
                    b.Navigation("BaiGiangs");

                    b.Navigation("BinhLuans");

                    b.Navigation("LopHocPhan_SinhViens");

                    b.Navigation("LopHocPhans");

                    b.Navigation("OTPs");

                    b.Navigation("ThongBaos");
                });

            modelBuilder.Entity("Lecture_web.Models.ThongBaoModels", b =>
                {
                    b.Navigation("BinhLuans");
                });
#pragma warning restore 612, 618
        }
    }
}
